<?php declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20190730172554 extends AbstractMigration
{
    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE statsms (id INT AUTO_INCREMENT NOT NULL, datoper DATETIME NOT NULL, datestat DATE NOT NULL, solde DOUBLE PRECISION NOT NULL, nbresms INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('DROP TABLE abonnement_save');
        $this->addSql('ALTER TABLE compte CHANGE nomclient nomclient VARCHAR(50) DEFAULT NULL, CHANGE datfrmcli datfrmcli VARCHAR(10) DEFAULT NULL, CHANGE tel tel VARCHAR(66) DEFAULT NULL');
        $this->addSql('ALTER TABLE user CHANGE roles roles JSON NOT NULL, CHANGE telephone telephone VARCHAR(30) DEFAULT NULL, CHANGE employeeid employeeid VARCHAR(5) DEFAULT NULL, CHANGE description description VARCHAR(60) DEFAULT NULL, CHANGE manager manager VARCHAR(150) DEFAULT NULL');
        $this->addSql('ALTER TABLE message CHANGE validepar_id validepar_id INT DEFAULT NULL, CHANGE datevalid1 datevalid1 DATETIME DEFAULT NULL, CHANGE datevalid2 datevalid2 DATETIME DEFAULT NULL, CHANGE datediffu datediffu DATETIME DEFAULT NULL, CHANGE tel tel VARCHAR(15) DEFAULT NULL');
        $this->addSql('ALTER TABLE outgoing CHANGE sendsms_at sendsms_at DATETIME DEFAULT NULL, CHANGE letest letest JSON DEFAULT NULL, CHANGE bulk_id bulk_id VARCHAR(40) DEFAULT NULL, CHANGE send_groupid send_groupid SMALLINT DEFAULT NULL, CHANGE send_groupname send_groupname VARCHAR(30) DEFAULT NULL, CHANGE send_id send_id SMALLINT DEFAULT NULL, CHANGE send_name send_name VARCHAR(50) DEFAULT NULL, CHANGE send_description send_description VARCHAR(150) DEFAULT NULL, CHANGE sms_count sms_count SMALLINT DEFAULT NULL, CHANGE report_sentat report_sentat DATETIME DEFAULT NULL, CHANGE report_doneat report_doneat DATETIME DEFAULT NULL, CHANGE report_mccmnc report_mccmnc VARCHAR(20) DEFAULT NULL, CHANGE report_pricepermessage report_pricepermessage INT DEFAULT NULL, CHANGE report_currency report_currency VARCHAR(20) DEFAULT NULL, CHANGE report_status_groupid report_status_groupid INT DEFAULT NULL, CHANGE report_status_groupname report_status_groupname VARCHAR(50) DEFAULT NULL, CHANGE report_status_id report_status_id INT DEFAULT NULL, CHANGE report_status_name report_status_name VARCHAR(80) DEFAULT NULL, CHANGE report_status_description report_status_description VARCHAR(100) DEFAULT NULL, CHANGE report_error_groupid report_error_groupid VARCHAR(1) DEFAULT NULL, CHANGE report_error_groupname report_error_groupname VARCHAR(50) DEFAULT NULL, CHANGE report_error_id report_error_id INT DEFAULT NULL, CHANGE report_error_name report_error_name VARCHAR(50) DEFAULT NULL, CHANGE report_error_description report_error_description VARCHAR(50) DEFAULT NULL, CHANGE report_error_permanent report_error_permanent VARCHAR(20) DEFAULT NULL, CHANGE applic applic VARCHAR(150) DEFAULT NULL');
        $this->addSql('ALTER TABLE abonnement CHANGE datfrm datfrm DATE DEFAULT NULL, CHANGE datvalidation datvalidation DATE DEFAULT NULL, CHANGE datedesactif datedesactif DATE DEFAULT NULL, CHANGE datefinabon datefinabon DATE DEFAULT NULL, CHANGE userresili userresili VARCHAR(35) DEFAULT NULL, CHANGE nom_userresili nom_userresili VARCHAR(25) DEFAULT NULL');
        $this->addSql('ALTER TABLE chargesms CHANGE datetrt datetrt DATETIME DEFAULT NULL');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE abonnement_save (id INT DEFAULT 0 NOT NULL, agence VARCHAR(5) NOT NULL COLLATE utf8mb4_unicode_ci, agencelib VARCHAR(50) NOT NULL COLLATE utf8mb4_unicode_ci, rm VARCHAR(25) NOT NULL COLLATE utf8mb4_unicode_ci, typ VARCHAR(1) NOT NULL COLLATE utf8mb4_unicode_ci, typlib VARCHAR(9) NOT NULL COLLATE utf8mb4_unicode_ci, client VARCHAR(25) NOT NULL COLLATE utf8mb4_unicode_ci, phone VARCHAR(11) NOT NULL COLLATE utf8mb4_unicode_ci, compte VARCHAR(11) NOT NULL COLLATE utf8mb4_unicode_ci, datouv DATE NOT NULL, datfrm DATE DEFAULT \'NULL\', typcptlib VARCHAR(32) NOT NULL COLLATE utf8mb4_unicode_ci, ncg VARCHAR(6) NOT NULL COLLATE utf8mb4_unicode_ci, libelle VARCHAR(32) NOT NULL COLLATE utf8mb4_unicode_ci, formule VARCHAR(16) NOT NULL COLLATE utf8mb4_unicode_ci, databon DATE NOT NULL, userabon VARCHAR(35) NOT NULL COLLATE utf8mb4_unicode_ci, nom_userabon VARCHAR(25) NOT NULL COLLATE utf8mb4_unicode_ci, valide TINYINT(1) NOT NULL, datvalidation DATE DEFAULT \'NULL\', uservalide VARCHAR(2) NOT NULL COLLATE utf8mb4_unicode_ci, nom_uservalide VARCHAR(25) NOT NULL COLLATE utf8mb4_unicode_ci, datactif DATE NOT NULL, useractif VARCHAR(35) NOT NULL COLLATE utf8mb4_unicode_ci, nom_useractif VARCHAR(25) NOT NULL COLLATE utf8mb4_unicode_ci, actif TINYINT(1) NOT NULL, datedesactif DATE DEFAULT \'NULL\', datefinabon DATE DEFAULT \'NULL\', userresili VARCHAR(35) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, nom_userresili VARCHAR(25) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, exonere_facture_pull TINYINT(1) NOT NULL, exonere_facture_push TINYINT(1) NOT NULL, save_date DATETIME DEFAULT \'NULL\') DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('DROP TABLE statsms');
        $this->addSql('ALTER TABLE abonnement CHANGE datfrm datfrm DATE DEFAULT \'NULL\', CHANGE datvalidation datvalidation DATE DEFAULT \'NULL\', CHANGE datedesactif datedesactif DATE DEFAULT \'NULL\', CHANGE datefinabon datefinabon DATE DEFAULT \'NULL\', CHANGE userresili userresili VARCHAR(35) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE nom_userresili nom_userresili VARCHAR(25) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci');
        $this->addSql('ALTER TABLE chargesms CHANGE datetrt datetrt DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE compte CHANGE nomclient nomclient VARCHAR(50) DEFAULT \'NULL\' COLLATE latin1_swedish_ci, CHANGE datfrmcli datfrmcli VARCHAR(10) DEFAULT \'NULL\' COLLATE latin1_swedish_ci, CHANGE tel tel VARCHAR(66) DEFAULT \'NULL\' COLLATE latin1_swedish_ci');
        $this->addSql('ALTER TABLE message CHANGE validepar_id validepar_id INT DEFAULT NULL, CHANGE datevalid1 datevalid1 DATETIME DEFAULT \'NULL\', CHANGE datevalid2 datevalid2 DATETIME DEFAULT \'NULL\', CHANGE datediffu datediffu DATETIME DEFAULT \'NULL\', CHANGE tel tel VARCHAR(15) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci');
        $this->addSql('ALTER TABLE outgoing CHANGE sendsms_at sendsms_at DATETIME DEFAULT \'NULL\', CHANGE letest letest LONGTEXT DEFAULT NULL COLLATE utf8mb4_bin, CHANGE bulk_id bulk_id VARCHAR(40) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE send_groupid send_groupid SMALLINT DEFAULT NULL, CHANGE send_groupname send_groupname VARCHAR(30) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE send_id send_id SMALLINT DEFAULT NULL, CHANGE send_name send_name VARCHAR(50) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE send_description send_description VARCHAR(150) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE sms_count sms_count SMALLINT DEFAULT NULL, CHANGE report_sentat report_sentat DATETIME DEFAULT \'NULL\', CHANGE report_doneat report_doneat DATETIME DEFAULT \'NULL\', CHANGE report_mccmnc report_mccmnc VARCHAR(20) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE report_pricepermessage report_pricepermessage INT DEFAULT NULL, CHANGE report_currency report_currency VARCHAR(20) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE report_status_groupid report_status_groupid INT DEFAULT NULL, CHANGE report_status_groupname report_status_groupname VARCHAR(50) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE report_status_id report_status_id INT DEFAULT NULL, CHANGE report_status_name report_status_name VARCHAR(80) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE report_status_description report_status_description VARCHAR(100) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE report_error_groupid report_error_groupid VARCHAR(1) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE report_error_groupname report_error_groupname VARCHAR(50) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE report_error_id report_error_id INT DEFAULT NULL, CHANGE report_error_name report_error_name VARCHAR(50) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE report_error_description report_error_description VARCHAR(50) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE report_error_permanent report_error_permanent VARCHAR(20) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE applic applic VARCHAR(150) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci');
        $this->addSql('ALTER TABLE user CHANGE roles roles LONGTEXT NOT NULL COLLATE utf8mb4_bin, CHANGE telephone telephone VARCHAR(30) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE employeeid employeeid VARCHAR(5) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE description description VARCHAR(60) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE manager manager VARCHAR(150) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci');
    }
}
